// Code generated by MockGen. DO NOT EDIT.
// Source: storage.go

// Package mock_ports is a generated GoMock package.
package mock_ports

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	ports "github.com/mahadeva604/grpc-broker/internal/ports"
)

// MockStorage is a mock of Storage interface.
type MockStorage struct {
	ctrl     *gomock.Controller
	recorder *MockStorageMockRecorder
}

// MockStorageMockRecorder is the mock recorder for MockStorage.
type MockStorageMockRecorder struct {
	mock *MockStorage
}

// NewMockStorage creates a new mock instance.
func NewMockStorage(ctrl *gomock.Controller) *MockStorage {
	mock := &MockStorage{ctrl: ctrl}
	mock.recorder = &MockStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorage) EXPECT() *MockStorageMockRecorder {
	return m.recorder
}

// GetTopic mocks base method.
func (m *MockStorage) GetTopic(topicName string) (ports.Topic, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTopic", topicName)
	ret0, _ := ret[0].(ports.Topic)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTopic indicates an expected call of GetTopic.
func (mr *MockStorageMockRecorder) GetTopic(topicName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTopic", reflect.TypeOf((*MockStorage)(nil).GetTopic), topicName)
}

// GreateTopic mocks base method.
func (m *MockStorage) GreateTopic(topicName string, queueLength int) (ports.Topic, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GreateTopic", topicName, queueLength)
	ret0, _ := ret[0].(ports.Topic)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GreateTopic indicates an expected call of GreateTopic.
func (mr *MockStorageMockRecorder) GreateTopic(topicName, queueLength interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GreateTopic", reflect.TypeOf((*MockStorage)(nil).GreateTopic), topicName, queueLength)
}
