name: Test and build

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
    
    - name: Verify dependencies
      run: go mod verify
        
    - name: Build server
      run: go build -o grpc-broker -v cmd/server/main.go
    
    - name: Build consumer
      run: go build -o consumer -v cmd/consumer/main.go
    
    - name: Build producer
      run: go build -o producer -v cmd/producer/main.go
      
    - name: Run go vet
      run: go vet ./...
    
    - name: Install golint
      run: go install golang.org/x/lint/golint@latest
    
    - name: Run golint
      run: golint ./...
    
    - name: Run testing
      run: go test -race ./...
